version: '3.0'

services:

  httpd:
    build: ./
    container_name: 'httpd'
    ports:
      - '8050:8050'

  mysql:
    image: 'mysql:5.7'
    container_name: 'mysql'
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'segu-web-1234'
      MYSQL_DATABASE: 'segu_web'
    ports:
      - '3306:3306'

volumes:
  db_data: